import Head from 'next/head'
import { signIn } from "next-auth/react";
import axios from 'axios';
import { Notify } from 'notiflix/build/notiflix-notify-aio';

export default function Home() {

    const registerUser = e => {
        e.preventDefault()
        const name = e.target.name.value
        const email = e.target.email.value
        const password = e.target.password.value

        const u = { "name": name, "email": email, "password": password }
        console.log(u)
        axios.post("http://localhost:8000/api/user", u).then(function (response) {
            Notify.success('Usuario cadastrado!')
        });
    }

    return (
        <div>
            <Head>
                <title>Cadastro</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="container">
                    <div className="boxl">
                        <h2>Cadastre-se</h2>
                        <div className="register">
                            <form method='post' onSubmit={registerUser}>
                                <label>Nome</label><br />
                                <input name='name' id='name' type={'text'} /><br />
                                <label>E-mail</label><br />
                                <input name='email' id='email' type={'email'} /><br />
                                <label>Senha</label><br />
                                <input name='password' id='password' type={'password'} /><br />
                                <button type="submit" className="btn btn-success">
                                    Registrar
                                </button>
                            </form>
                        </div>
                        <div className="vls">
                            <span className="vl-innertext">ou</span>
                        </div>
                        <div className='login-social'>
                            <a href="#" className="fb btns" onClick={() => {
                                signIn("facebook", { callbackUrl: "http://localhost:3000/welcome" })
                            }
                            }>
                                <i className="fa fa-facebook fa-fw"></i>
                            </a>
                            <a href="#" className="github btns" onClick={() => {
                                signIn("github", { callbackUrl: "http://localhost:3000/welcome" })
                            }
                            }>
                                <i className="fa fa-github fa-gh"></i>
                            </a>
                            <a href="#" className="google btns" onClick={() => {
                                signIn("google", { callbackUrl: "http://localhost:3000/welcome" })
                            }
                            }>
                                <i className="fa fa-google fa-fw"></i>
                            </a>
                            <a href="#" className="insta btns" onClick={() => {
                                signIn("instagram", { callbackUrl: "http://localhost:3000/welcome" })
                            }
                            }>
                                <i className="fa fa-instagram fa-ig"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}