import Head from 'next/head'
import axios from 'axios';
import { signIn, getSession } from 'next-auth/react';
import { useState } from 'react';
import Link from 'next/link';

export default function Login() {

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const onSubmit = async () => {
        signIn('credentials', {
            email: email,
            password: password,
        })
            .then(res => {
                console.log(res);
            })
            .catch(err => {
                console.error(err);
            });
    };
    return (
        <div>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="container">
                    <div className="box">
                        <h2>Login</h2>
                        <p className="d-grid gap-2">
                            <button className="btn btn-dark" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseClients" aria-expanded="false" aria-controls="collapseExample">
                                Usuario
                            </button>
                            <Link href='http://localhost:8000/admin' className="btn btn-dark" aria-expanded="false" type="button">
                                Admin
                            </Link>
                            <h5>Ainda não tem conta? <Link href='/'>Registre-se aqui</Link></h5>
                        </p>
                        <div className="collapse" id="collapseClients">
                            <div className="card card-body">
                                <div className="register">
                                    <form onSubmit={onSubmit}>
                                        <label>E-mail</label><br />
                                        <input onChange={(e) => setEmail(e.target.value)}
                                            value={email} name='email' id='email' type={'email'} /><br />
                                        <label>Senha</label><br />
                                        <input onChange={(e) => setPassword(e.target.value)}
                                            value={password} name='password' id='password' type={'password'} /><br />
                                        <button type="submit" className="btn btn-success" onClick={() => { signIn("credentials", { email: document.getElementById("email"), password: document.getElementById("password"), callbackUrl: "http://localhost:3000/welcome" }) }}>
                                            Logar
                                        </button>
                                    </form>

                                </div>
                                <div className="vl">
                                    <span className="vl-innertext">ou</span>
                                </div>
                                <div className='login-social'>
                                    <a href="#" className="fb btns" onClick={() => {
                                        signIn("facebook")
                                    }
                                    }>
                                        <i className="fa fa-facebook fa-fw"></i>
                                    </a>
                                    <a href="#" className="github btns" onClick={() => {
                                        signIn("github")
                                    }
                                    }>
                                        <i className="fa fa-github fa-gh"></i>
                                    </a>
                                    <a href="#" className="google btns" onClick={() => {
                                        signIn("google")
                                    }
                                    }>
                                        <i className="fa fa-google fa-fw"></i>
                                    </a>
                                    <a href="#" className="insta btns" onClick={() => {
                                        signIn("instagram")
                                    }
                                    }>
                                        <i className="fa fa-instagram fa-ig"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export const getServerSideProps = async (context) => {
    const session = await getSession(context);
    if (session) {
        return {
            redirect: {
                destination: '/welcome',
                permanent: false
            }
        };
    };
    return {
        props: { session }
    }
}