import Head from 'next/head'
import { getSession, signOut, useSession } from "next-auth/react";

export default function Welcome() {

    const { data: session } = useSession();
    return (
        <div>
            <Head>
                <title>Bem-vindo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="container">
                    <div className="box">
                        <h1>Bem-vindo(a) {session?.user?.name}</h1><br/>
                        <button className='btn btn-danger' onClick={() => signOut()} >Logout</button>
                    </div>
                </div>
            </main>
        </div>
    )
}

export const getServerSideProps = async (context) => {
    const session = await getSession(context);
    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        };
    };
    return {
        props: { session }
    }
}